### ISSUE TITLE
add some easy way to specify runtime size of io-structure

### ISSUE THREAD

**Issue by 3b** [Shinmera/binary-structures#9]
lots of formats encode sizes of things into the file, so would be nice to be able to specify size of a structure in terms of `SLOT` within the `define-io-structure` (instead of manually writing a method on `octet-size` or `octet-size-form`).
Not sure if it would be better as a "name and options" form, or an extra option to the slot.
maybe something like
```lisp
(define-io-structure (tagged :octet-size (+ (slot size) 8))
  (size :uint32)
  (tag :uint32)
  (contents (case tag ...)))
```

**Comment by Shinmera** [comment]
As per aa5e10c this can now be done:

```lisp
(bs:define-io-structure tags
  :octet-size (+ (bs:slot size) 8)
  (size :uint32)
  (tag :uint32))
  ```

though the backend does not yet usefully use this to allow things like

```lisp
(bs:define-io-structure tags
  :octet-size (+ (bs:slot size) 8)
  (size :uint32)
  (tag :uint32)
  (payload (vector :uint8)))
```

See #3
